#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "Please run as root."
	exit 0
fi

REPO=$(dirname "$0")

for location in "boot" "etc" "usr" "var"; do
	rsync -Kahv "$REPO/$location/" "/$location"
done

for terminfo in "$REPO"/terminfo/*; do
	tic -sx $terminfo
done
