#!/bin/sh

[ "$(id -u)" -eq 0 ] || {
	echo "Please run as root."
	exit 1
}

REPO=$(dirname "$0")

for directory in "boot" "etc" "usr" "var"; do
	[ "$(command -v rsync)" ] || {
		echo 'rsync is not founded. is it installed?'
		exit 1
	}
	[ -d "$directory" ] && rsync -ahKv "$REPO/$directory/" "/$directory"
done

for terminfo in "$REPO"/terminfo/*; do
	[ "$(command -v tic)" ] || {
		echo 'tic is not founded. is it installed?'
		exit 1
	}
	tic -sx "$terminfo"
done
